#!/bin/python3
tarot = {
  'Adjustment': {
    'title': 'Adjustment',
    'class': 'TRUMPS',
  },
  'Art': {
    'title': 'Art',
    'class': 'TRUMPS',
  },
  'Death': {
    'title': 'Death',
    'class': 'TRUMPS',
  },
  'Fortune': {
    'title': 'Fortune',
    'class': 'TRUMPS',
  },
  'Lust': {
    'title': 'Lust',
    'class': 'TRUMPS',
  },
  'TheAeon': {
    'title': 'TheAeon',
    'class': 'TRUMPS',
  },
  'TheChariot': {
    'title': 'TheChariot',
    'class': 'TRUMPS',
  },
  'TheDevil': {
    'title': 'TheDevil',
    'class': 'TRUMPS',
  },
  'TheEmperor': {
    'title': 'TheEmperor',
    'class': 'TRUMPS',
  },
  'TheEmpress': {
    'title': 'TheEmpress',
    'class': 'TRUMPS',
  },
  'TheFool': {
    'title': 'TheFool',
    'class': 'TRUMPS',
  },
  'TheHangedMan': {
    'title': 'TheHangedMan',
    'class': 'TRUMPS',
  },
  'TheHermit': {
    'title': 'TheHermit',
    'class': 'TRUMPS',
  },
  'TheHierophant': {
    'title': 'TheHierophant',
    'class': 'TRUMPS',
  },
  'TheLovers': {
    'title': 'TheLovers',
    'class': 'TRUMPS',
  },
  'TheMagus': {
    'title': 'TheMagus',
    'class': 'TRUMPS',
  },
  'TheMoon': {
    'title': 'TheMoon',
    'class': 'TRUMPS',
  },
  'ThePriestess': {
    'title': 'ThePriestess',
    'class': 'TRUMPS',
  },
  'TheStar': {
    'title': 'TheStar',
    'class': 'TRUMPS',
  },
  'TheSun': {
    'title': 'TheSun',
    'class': 'TRUMPS',
  },
  'TheTower': {
    'title': 'TheTower',
    'class': 'TRUMPS',
  },
  'TheUniverse': {
    'title': 'TheUniverse',
    'class': 'TRUMPS',
  },
  'KnightOfWands': {
    'title': 'KnightOfWands',
    'class': 'COURTS',
    'order': 'KNIGHTS',
    'suit': 'WANDS',
  },
  'QueenOfWands': {
    'title': 'QueenOfWands',
    'class': 'COURTS',
    'order': 'QUEENS',
    'suit': 'WANDS',
  },
  'PrinceOfWands': {
    'title': 'PrinceOfWands',
    'class': 'COURTS',
    'order': 'PRINCE',
    'suit': 'WANDS',
  },
  'PrincessOfWands': {
    'title': 'PrincessOfWands',
    'class': 'COURTS',
    'order': 'PRINCESS',
    'suit': 'WANDS',
  },
  'KnightOfCups': {
    'title': 'KnightOfCups',
    'class': 'COURTS',
    'order': 'KNIGHTS',
    'suit': 'CUPS',
  },
  'QueenOfCups': {
    'title': 'QueenOfCups',
    'class': 'COURTS',
    'order': 'QUEENS',
    'suit': 'CUPS',
  },
  'PrinceOfCups': {
    'title': 'PrinceOfCups',
    'class': 'COURTS',
    'order': 'PRINCE',
    'suit': 'CUPS',
  },
  'PrincessOfCups': {
    'title': 'PrincessOfCups',
    'class': 'COURTS',
    'order': 'PRINCESS',
    'suit': 'CUPS',
  },
  'KnightOfSwords': {
    'title': 'KnightOfSwords',
    'class': 'COURTS',
    'order': 'KNIGHTS',
    'suit': 'SWORDS',
  },
  'QueenOfSwords': {
    'title': 'QueenOfSwords',
    'class': 'COURTS',
    'order': 'QUEENS',
    'suit': 'SWORDS',
  },
  'PrinceOfSwords': {
    'title': 'PrinceOfSwords',
    'class': 'COURTS',
    'order': 'PRINCE',
    'suit': 'SWORDS',
  },
  'PrincessOfSwords': {
    'title': 'PrincessOfSwords',
    'class': 'COURTS',
    'order': 'PRINCESS',
    'suit': 'SWORDS',
  },
  'KnightOfDisks': {
    'title': 'KnightOfDisks',
    'class': 'COURTS',
    'order': 'KNIGHTS',
    'suit': 'DISKS',
  },
  'QueenOfDisks': {
    'title': 'QueenOfDisks',
    'class': 'COURTS',
    'order': 'QUEENS',
    'suit': 'DISKS',
  },
  'PrinceOfDisks': {
    'title': 'PrinceOfDisks',
    'class': 'COURTS',
    'order': 'PRINCE',
    'suit': 'DISKS',
  },
  'PrincessOfDisks': {
    'title': 'PrincessOfDisks',
    'class': 'COURTS',
    'order': 'PRINCESS',
    'suit': 'DISKS',
  },
  'AceOfWands': {
    'title': 'AceOfWands',
    'class': 'MINORS',
    'order': 'ACES',
    'suit': 'WANDS',
  },
  'TwoOfWands': {
    'title': 'Dominion',
    'class': 'MINORS',
    'order': 'TWOS',
    'suit': 'WANDS',
  },
  'ThreeOfWands': {
    'title': 'Virtue',
    'class': 'MINORS',
    'order': 'THREES',
    'suit': 'WANDS',
  },
  'FourOfWands': {
    'title': 'Completion',
    'class': 'MINORS',
    'order': 'FOURS',
    'suit': 'WANDS',
  },
  'FiveOfWands': {
    'title': 'Strife',
    'class': 'MINORS',
    'order': 'FIVES',
    'suit': 'WANDS',
  },
  'SixOfWands': {
    'title': 'Victory',
    'class': 'MINORS',
    'order': 'SIXES',
    'suit': 'WANDS',
  },
  'SevenOfWands': {
    'title': 'Valour',
    'class': 'MINORS',
    'order': 'SEVENS',
    'suit': 'WANDS',
  },
  'EightOfWands': {
    'title': 'Swiftness',
    'class': 'MINORS',
    'order': 'EIGHTS',
    'suit': 'WANDS',
  },
  'NineOfWands': {
    'title': 'Strength',
    'class': 'MINORS',
    'order': 'NINES',
    'suit': 'WANDS',
  },
  'TenOfWands': {
    'title': 'Oppression',
    'class': 'MINORS',
    'order': 'TENS',
    'suit': 'WANDS',
  },
  'AceOfCups': {
    'title': 'AceOfCups',
    'class': 'MINORS',
    'order': 'ACES',
    'suit': 'CUPS',
  },
  'TwoOfCups': {
    'title': 'Love',
    'class': 'MINORS',
    'order': 'TWOS',
    'suit': 'CUPS',
  },
  'ThreeOfCups': {
    'title': 'Abundance',
    'class': 'MINORS',
    'order': 'THREES',
    'suit': 'CUPS',
  },
  'FourOfCups': {
    'title': 'Luxury',
    'class': 'MINORS',
    'order': 'FOURS',
    'suit': 'CUPS',
  },
  'FiveOfCups': {
    'title': 'Disappointment',
    'class': 'MINORS',
    'order': 'FIVES',
    'suit': 'CUPS',
  },
  'SixOfCups': {
    'title': 'Pleasure',
    'class': 'MINORS',
    'order': 'SIXES',
    'suit': 'CUPS',
  },
  'SevenOfCups': {
    'title': 'Debauch',
    'class': 'MINORS',
    'order': 'SEVENS',
    'suit': 'CUPS',
  },
  'EightOfCups': {
    'title': 'Indolence',
    'class': 'MINORS',
    'order': 'EIGHTS',
    'suit': 'CUPS',
  },
  'NineOfCups': {
    'title': 'Happiness',
    'class': 'MINORS',
    'order': 'NINES',
    'suit': 'CUPS',
  },
  'TenOfCups': {
    'title': 'Satiety',
    'class': 'MINORS',
    'order': 'TENS',
    'suit': 'CUPS',
  },
  'AceOfSwords': {
    'title': 'AceOfSwords',
    'class': 'MINORS',
    'order': 'ONES',
    'suit': 'SWORDS',
  },
  'TwoOfSwords': {
    'title': 'Peace',
    'class': 'MINORS',
    'order': 'TWOS',
    'suit': 'SWORDS',
  },
  'ThreeOfSwords': {
    'title': 'Sorrow',
    'class': 'MINORS',
    'order': 'THREES',
    'suit': 'SWORDS',
  },
  'FourOfSwords': {
    'title': 'Truce',
    'class': 'MINORS',
    'order': 'FOURS',
    'suit': 'SWORDS',
  },
  'FiveOfSwords': {
    'title': 'Defeat',
    'class': 'MINORS',
    'order': 'FIVES',
    'suit': 'SWORDS',
  },
  'SixOfSwords': {
    'title': 'Science',
    'class': 'MINORS',
    'order': 'SIXES',
    'suit': 'SWORDS',
  },
  'SevenOfSwords': {
    'title': 'Futility',
    'class': 'MINORS',
    'order': 'SEVENS',
    'suit': 'SWORDS',
  },
  'EightOfSwords': {
    'title': 'Interference',
    'class': 'MINORS',
    'order': 'EIGHTS',
    'suit': 'SWORDS',
  },
  'NineOfSwords': {
    'title': 'Cruelty',
    'class': 'MINORS',
    'order': 'NINES',
    'suit': 'SWORDS',
  },
  'TenOfSwords': {
    'title': 'Ruin',
    'class': 'MINORS',
    'order': 'TENS',
    'suit': 'SWORDS',
  },
  'AceOfDisks': {
    'title': 'AceOfDisks',
    'class': 'MINORS',
    'order': 'ACES',
    'suit': 'DISKS',
  },
  'TwoOfDisks': {
    'title': 'Change',
    'class': 'MINORS',
    'order': 'TWOS',
    'suit': 'DISKS',
  },
  'ThreeOfDisks': {
    'title': 'Works',
    'class': 'MINORS',
    'order': 'THREES',
    'suit': 'DISKS',
  },
  'FourOfDisks': {
    'title': 'Power',
    'class': 'MINORS',
    'order': 'FOURS',
    'suit': 'DISKS',
  },
  'FiveOfDisks': {
    'title': 'Worry',
    'class': 'MINORS',
    'order': 'FIVES',
    'suit': 'DISKS',
  },
  'SixOfDisks': {
    'title': 'Success',
    'class': 'MINORS',
    'order': 'SIXES',
    'suit': 'DISKS',
  },
  'SevenOfDisks': {
    'title': 'Failure',
    'class': 'MINORS',
    'order': 'SEVENS',
    'suit': 'DISKS',
  },
  'EightOfDisks': {
    'title': 'Prudence',
    'class': 'MINORS',
    'order': 'EIGHTS',
    'suit': 'DISKS',
  },
  'NineOfDisks': {
    'title': 'Gain',
    'class': 'MINORS',
    'order': 'NINES',
    'suit': 'DISKS',
  },
  'TenOfDisks': {
    'title': 'Wealth',
    'class': 'MINORS',
    'order': 'TENS',
    'suit': 'DISKS',
  }
}